/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime=false` (hash: 8cdcade51bcefc5757e9c1e4b9dbb9ec)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/worker");
	}
	interface Env {
		GEMINI_MODEL: "gemini-2.5-flash";
		GEMINI_API_KEY: string;
		APP_URL: string;
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_MODEL" | "GEMINI_API_KEY" | "APP_URL">> {}
}
